services:
  - type: web
    name: movietrakk-app
    runtime: maven
    buildCommand: mvn clean install -DskipTests
    startCommand: java -jar target/MovieTrakk-1.0-SNAPSHOT.jar --server.port=$PORT
    envVars:
      - key: JAVA_VERSION
        value: 21
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: SUPABASE_DB_URL
        fromDatabase:
          name: movietrakk-db
          property: jdbcConnectionString
      - key: SUPABASE_DB_USER
        fromDatabase:
          name: movietrakk-db
          property: user
      - key: SUPABASE_DB_PASSWORD
        fromDatabase:
          name: movietrakk-db
          property: password

databases:
  - name: movietrakk-db
    plan: free