services:
  - type: web
    name: movietrakk-app
    plan: free
    runtime: docker
    envVars:
      - key: JAVA_VERSION
        value: 21
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: SUPABASE_DB_URL
      - key: SUPABASE_DB_USER
      - key: SUPABASE_DB_PASSWORD
      - key: DB_POOL_MAX_SIZE
        value: 5
      - key: DB_POOL_MIN_IDLE
        value: 1